[package]
name = "litepcie"
version = "0.1.0"
edition = "2021"

[dependencies]
pci-driver = "0.1.4"
serde = { version = "1.0.195", features = ["derive"] }
thiserror = "1.0.56"

[dev-dependencies]
anyhow = "1.0.79"
clap = { version = "4.4.17", features = ["derive"] }
serde_json = "1.0.111"
